# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-21 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'navigation record',
                'verbose_name_plural': 'navigation records',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'vehicles',
                'verbose_name_plural': 'vehicles',
            },
        ),
        migrations.AddField(
            model_name='navigationrecord',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigation_records', to='vehicle.Vehicle'),
        ),
    ]
